# sutta-training-dashboard.py
# Version: 1.0.0
# Unified Active Session Keep-Alive, Sheets Sync, & Live Local Audio Preview Dashboard.
# Paste this code directly into your Google Colab Keep-Alive cell.
# It syncs uat_metrics.csv to Google Sheets while rendering local HTML5 playback widgets.

import os
import time
import pandas as pd
import IPython.display as ipd
from google.colab import auth
from google.auth import default
import gspread

# 1. Define File Paths
PIPER_TRAINING = "/content/drive/MyDrive/piper_training"
METRICS_CSV = os.path.join(PIPER_TRAINING, "uat_metrics.csv")
PREVIEW_DIR = "/content/previews"  # Local volatile NVMe preview directory
SHEET_NAME = "SuttaPlayer_UAT_Convergence"

def print_header(epoch, val_loss):
    print("=" * 65)
    print("          SUTTAPLAYER LIVE UAT MONITORING DASHBOARD          ")
    print("=" * 65)
    print(f"  * Latest Epoch: {epoch:<5} | Global Validation Loss: {val_loss:<8}")
    print("-" * 65)

def render_dashboard(ws, last_logged_epoch):
    # Clear the notebook cell output to draw a fresh frame
    ipd.clear_output(wait=True)
    
    # Read local CSV to print CLI state
    if os.path.exists(METRICS_CSV):
        try:
            df = pd.read_csv(METRICS_CSV)
            if not df.empty:
                latest_row = df.iloc[-1]
                epoch = latest_row.get("epoch", "Unknown")
                val_loss = latest_row.get("val_loss", "N/A")
                print_header(epoch, val_loss)
                
                # Print a clean, formatted UAT status table in stdout
                print(f"{'Probe / Metric Name':<28} | {'Convergence Status':<22}")
                print("-" * 65)
                for col in df.columns:
                    if col not in ["timestamp", "epoch", "val_loss"]:
                        val = latest_row[col]
                        # Colorize output logically (PASS if 100%, warning if climbing)
                        try:
                            val_float = float(val)
                            if val_float >= 100.0:
                                status = "🟢 PASS (100%)"
                            elif val_float > 0.0:
                                status = f"🟡 CLIMBING ({val_float:.1f}%)"
                            else:
                                status = "🔴 COLD (0.0%)"
                        except ValueError:
                            status = f" {val}"
                        print(f"  {col:<26} | {status:<22}")
                print("-" * 65)
                print(f"  Spreadsheet Status: Synced up to Epoch {last_logged_epoch}")
        except Exception as e:
            print(f"  [WARNING] Could not read local metrics CSV: {e}")
    else:
        print("Waiting for uat_metrics.csv to be generated by the trainer...")

    # Render HTML5 Playback buttons for latest local NVMe wav previews
    if os.path.exists(PREVIEW_DIR):
        print("\n" + "=" * 65)
        print("           LIVE VOCAL PHONETIC PREVIEWS (0 TRASH BYTES)       ")
        print("=" * 65)
        try:
            preview_files = sorted([f for f in os.listdir(PREVIEW_DIR) if f.endswith(".wav")])
            if preview_files:
                for filename in preview_files:
                    # Label files clearly
                    friendly_name = filename.replace("_latest.wav", "").replace("probe_", "").replace("_", " ").title()
                    print(f"🔊 {friendly_name}:")
                    ipd.display(ipd.Audio(os.path.join(PREVIEW_DIR, filename)))
            else:
                print("  No preview WAV files found in /content/previews yet.")
        except Exception as e:
            print(f"  [WARNING] Could not access local previews: {e}")
    else:
        print("\n[Vocal Previews] Waiting for local NVMe previews directory (/content/previews) to be populated...")

def main():
    print("🔐 Authenticating Google Account for Sheets Sync...")
    try:
        auth.authenticate_user()
        creds, _ = default()
        gc = gspread.authorize(creds)
        
        try:
            sh = gc.open(SHEET_NAME)
        except gspread.exceptions.SpreadsheetNotFound:
            sh = gc.create(SHEET_NAME)
            print(f"✅ Created a new Google Sheets spreadsheet: '{SHEET_NAME}'")
            
        ws = sh.get_worksheet(0)
        
        # Determine the last logged row in Google Sheets
        try:
            sheet_values = ws.col_values(1)
            last_row = len(sheet_values)
        except Exception:
            last_row = 0
            
        print("💾 Keep-Alive & Sync Active. Entering dashboard loop...")
        time.sleep(3)
        
        last_logged_epoch = "None"
        
        while True:
            # Check for new data in CSV
            if os.path.exists(METRICS_CSV):
                try:
                    df = pd.read_csv(METRICS_CSV)
                    if len(df) > last_row:
                        # Fetch newly appended rows
                        new_data = df.iloc[last_row:].values.tolist()
                        for row in new_data:
                            ws.append_row(row)
                            last_logged_epoch = row[1]
                        last_row = len(df)
                except Exception as e:
                    # Ignore occasional write locks over gspread
                    pass
            
            # Redraw the entire dashboard (CLI status table + HTML5 players)
            render_dashboard(ws, last_logged_epoch)
            
            # Refresh interval matching Deno's cycle time
            time.sleep(30)
            
    except KeyboardInterrupt:
        print("\n⏹️ Sync and Dashboard Stopped.")

if __name__ == "__main__":
    main()
